### ISSUE TITLE
guides conversion error

### ISSUE THREAD

**Issue by afeld** [codio-templates/hello-codio-jupyter#6]
When I tried to use [this starter pack](https://codio.com/home/starter-packs/2ca374ce-c480-4c2c-8833-f01ff6f473d4), I got a prompt saying "This Guide is in an old format … We can automatically convert your Guide into the new format." I tried to do so, and got a "guides conversion error." It didn't give any more details. Thanks!

**Comment by pfe1223** [comment]
The best place to get help with this is with the support team. There are a couple of different ways you can get in touch with them:
https://docs.codio.com/instructors/getstarted/support/support.html#id1

**Comment by afeld** [comment]
Fixed by https://github.com/codio-templates/hello-codio-jupyter/pull/7.
